from settings.constants import *
from settings.models import *


settings = Settings(
    window=WindowSettings(
        width=WINDOW_WIDTH,
        height=WINDOW_HEIGHT,
        title=WINDOW_TITLE,
    ),
    map=MapSettings(
        background_color=Color(
            red=MAP_BACKGROUND_COLOR[0],
            green=MAP_BACKGROUND_COLOR[1],
            blue=MAP_BACKGROUND_COLOR[2]
        ),
        border_color=Color(
            red=MAP_BORDER_COLOR[0],
            green=MAP_BORDER_COLOR[1],
            blue=MAP_BORDER_COLOR[2]
        ),
        left=MAP_LEFT,
        top=MAP_TOP,
        width=MAP_WIDTH,
        height=MAP_HEIGHT,
        grid=Grid(
            border=Border(
                color=Color(
                    red=MAP_GRID_BORDER_COLOR[0],
                    green=MAP_GRID_BORDER_COLOR[1],
                    blue=MAP_GRID_BORDER_COLOR[2],
                ),
                thickness=MAP_GRID_BORDER_THICKNESS,
                enabled=MAP_GRID_BORDER_ENABLED,
                radius=MAP_GRID_BORDER_RADIUS,
            ),
            cell=Cell(
                width=MAP_GRID_CELL_WIDTH,
                height=MAP_GRID_CELL_HEIGHT,
            )
        )
    ),
    scoreboard=ScoreboardSettings(
        left=SCOREBOARD_LEFT,
        top=SCOREBOARD_TOP,
        width=SCOREBOARD_WIDTH,
        height=SCOREBOARD_HEIGHT,
        titles=SCOREBOARD_TITLES,
        background_color=Color(
            red=SCOREBOARD_BACKGROUND_COLOR[0],
            green=SCOREBOARD_BACKGROUND_COLOR[1],
            blue=SCOREBOARD_BACKGROUND_COLOR[2],
        ),
        section=Section(
            spacing=SCOREBOARD_SECTION_SPACING,
            padding=Padding(
                x=SCOREBOARD_SECTION_PADDING_X,
                y=SCOREBOARD_SECTION_PADDING_Y,
            ),
            border=Border(
                color=Color(
                    red=SCOREBOARD_SECTION_BORDER_COLOR[0],
                    green=SCOREBOARD_SECTION_BORDER_COLOR[1],
                    blue=SCOREBOARD_SECTION_BORDER_COLOR[2],
                ),
                thickness=SCOREBOARD_SECTION_BORDER_THICKNESS,
                enabled=SCOREBOARD_SECTION_BORDER_ENABLED,
                radius=SCOREBOARD_SECTION_BORDER_RADIUS,
            ),
            value=SCOREBOARD_SECTION_DEFAULT_VALUE,
            font_size=SCOREBOARD_SECTION_FONT_SIZE,
            font_color=Color(
                red=SCOREBOARD_SECTION_FONT_COLOR[0],
                green=SCOREBOARD_SECTION_FONT_COLOR[1],
                blue=SCOREBOARD_SECTION_FONT_COLOR[2],
            ),
            starting_point=Point(
                x=SCOREBOARD_SECTION_START_POINT_X,
                y=SCOREBOARD_SECTION_START_POINT_Y,
            )
        )
    ),
    snake=SnakeSettings(
        starting_energy=SNAKE_STARTING_ENERGY,
        head_color=Color(
            red=SNAKE_HEAD_COLOR[0],
            green=SNAKE_HEAD_COLOR[1],
            blue=SNAKE_HEAD_COLOR[2],
        ),
        body_color=Color(
            red=SNAKE_BODY_COLOR[0],
            green=SNAKE_BODY_COLOR[1],
            blue=SNAKE_BODY_COLOR[2],
        ),
    ),
    fruit=FruitSettings(
        apple=AppleFruit(
            color=Color(
                red=FRUIT_APPLE_COLOR[0],
                green=FRUIT_APPLE_COLOR[1],
                blue=FRUIT_APPLE_COLOR[2],
            ),
            drop_rate=FRUIT_APPLE_DROP_RATE,
            energy=FRUIT_APPLE_ENERGY,
            score=FRUIT_APPLE_SCORE,
        ),
        orange=OrangeFruit(
            color=Color(
                red=FRUIT_ORANGE_COLOR[0],
                green=FRUIT_ORANGE_COLOR[1],
                blue=FRUIT_ORANGE_COLOR[2],
            ),
            drop_rate=FRUIT_ORANGE_DROP_RATE,
            energy=FRUIT_ORANGE_ENERGY,
            score=FRUIT_ORANGE_SCORE,
        ),
        strawberry=StrawberryFruit(
            color=Color(
                red=FRUIT_STRAWBERRY_COLOR[0],
                green=FRUIT_STRAWBERRY_COLOR[1],
                blue=FRUIT_STRAWBERRY_COLOR[2],
            ),
            drop_rate=FRUIT_STRAWBERRY_DROP_RATE,
            energy=FRUIT_STRAWBERRY_ENERGY,
            score=FRUIT_STRAWBERRY_SCORE,
        )
    )
)