# WINDOW
WINDOW_WIDTH, WINDOW_HEIGHT = (1200, 900)
WINDOW_TITLE = "Hungry PYTHON 🐍"

# MAP
MAP_BACKGROUND_COLOR = (76, 18, 18)
MAP_BORDER_COLOR = (15, 15, 15)
MAP_LEFT, MAP_TOP = (0, 0)
MAP_WIDTH, MAP_HEIGHT = (900, 900)

# MAP - GRID
MAP_GRID_BORDER_COLOR = (0, 0, 0)
MAP_GRID_BORDER_THICKNESS = 1
MAP_GRID_BORDER_RADIUS = None
MAP_GRID_BORDER_ENABLED = True
MAP_GRID_CELL_WIDTH, MAP_GRID_CELL_HEIGHT = (20, 20)

# SCOREBOARD
SCOREBOARD_LEFT, SCOREBOARD_TOP = (900, 0)
SCOREBOARD_WIDTH, SCOREBOARD_HEIGHT = (300, 900)
SCOREBOARD_BACKGROUND_COLOR = (18, 18, 76)
SCOREBOARD_TITLES = (
    "SCORE",
    "HI-SCORE",
    "ENERGY",
)

# SCOREBOARD - SECTION
SCOREBOARD_SECTION_BORDER_COLOR = (0, 0, 0)
SCOREBOARD_SECTION_BORDER_RADIUS = 25
SCOREBOARD_SECTION_BORDER_THICKNESS = 3
SCOREBOARD_SECTION_BORDER_ENABLED = None
SCOREBOARD_SECTION_DEFAULT_VALUE = 0
SCOREBOARD_SECTION_FONT_SIZE = 20
SCOREBOARD_SECTION_PADDING_X, SCOREBOARD_SECTION_PADDING_Y = (45, 15)
SCOREBOARD_SECTION_SPACING = 10
SCOREBOARD_SECTION_START_POINT_X, SCOREBOARD_SECTION_START_POINT_Y = (0, 20)
SCOREBOARD_SECTION_FONT_COLOR = (123, 123, 123)

# SNAKE
SNAKE_STARTING_ENERGY = 100
SNAKE_BODY_COLOR = (225, 175, 209)
SNAKE_HEAD_COLOR = (173, 136, 198)

# FRUIT

# APPLE
FRUIT_APPLE_COLOR = (118, 205, 38)
FRUIT_APPLE_DROP_RATE = 70
FRUIT_APPLE_ENERGY = 5
FRUIT_APPLE_SCORE = 5

# ORANGE
FRUIT_ORANGE_COLOR = (255, 109, 10)
FRUIT_ORANGE_DROP_RATE = 20
FRUIT_ORANGE_ENERGY = 5
FRUIT_ORANGE_SCORE = 5

# STRAWBERRY
FRUIT_STRAWBERRY_COLOR = (216, 79, 79)
FRUIT_STRAWBERRY_DROP_RATE = 10
FRUIT_STRAWBERRY_ENERGY = 5
FRUIT_STRAWBERRY_SCORE = 5
