# WINDOW
WINDOW_WIDTH, WINDOW_HEIGHT = (800, 600)
WINDOW_TITLE = "Hungry PYTHON 🐍"

# MAP
MAP_BACKGROUND_COLOR = (76, 18, 18)
MAP_BORDER_COLOR = (15, 15, 15)
MAP_LEFT, MAP_TOP = (0, 0)
MAP_WIDTH, MAP_HEIGHT = (600, 600)

# MAP - GRID
MAP_GRID_BORDER_COLOR = (0, 0, 0)
MAP_GRID_BORDER_THICKNESS = 1
MAP_GRID_BORDER_ENABLED = True
MAP_GRID_CELL_WIDTH, MAP_GRID_CELL_HEIGHT = (15, 15)

# SCOREBOARD
SCOREBOARD_LEFT, SCOREBOARD_TOP = (600, 0)

# SNAKE
SNAKE_STARTING_ENERGY = 100

# FRUIT
